### ISSUE TITLE
iOS 8: Swift, Autolayout, Size Classes

### ISSUE THREAD

**Issue by cannyboy** [akosma/nib2objc#11]
Are there any plans for iOS 8 stuff in the future (Swift, Autolayout with constraints, Size Classes etc)

**Comment by jlebrech** [comment]
maybe splitting it into a nib processor + a plugin. so for example
nib2<plugin>

**Comment by akosma** [comment]
I'm working on a successor for nib2objc… stay tuned.

**Comment by jlebrech** [comment]
brilliant, I'd like to be able to create a nib2css as a plugin to the successor then

**Comment by muescha** [comment]
any news on this topic?

**Comment by helmut72** [comment]
any news for this? would be handy.
