### ISSUE TITLE
How to use this..??

### ISSUE THREAD

**Issue by cloudjanak** [akosma/nib2objc#12]

**Comment by akosma** [comment]
Could you please be more specific?

**Comment by cloudjanak** [comment]
how i can use this to generate .m file from xib..??
can you please add a working demo of xcode project..??

**Comment by akosma** [comment]
It's a command line tool. Use it from Terminal.app or iTerm2, for example. The README shows an example.

**Comment by mwurm93** [comment]
could you please give more detailed instructions on how to use from command line. could really use this tool!
