### ISSUE TITLE
trying sample throws wierd index beyond bounds error

### ISSUE THREAD

**Issue by stanchiang** [akosma/nib2objc#13]
I built the utility and tried running the sample from the command line, any help would be great. thanks

ran the following
$ ./nib2objc ~/Downloads/akosma-nib2objc-cde9b9e/Sample/TestViewController.xib > code.m

but got the error
2016-01-01 15:18:49.500 nib2objc[1468:52122] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayI objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 2]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00007fff94c0e03c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff8961e76e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff94ae5bce -[__NSArrayI objectAtIndex:] + 190
    3   nib2objc                            0x000000010153894b -[NSNumber(Nib2ObjcExtensions) tableViewCellSeparatorStyleString] + 139
    4   nib2objc                            0x0000000101543baf -[UITableViewProcessor processKey:value:] + 399
    5   nib2objc                            0x000000010153d401 -[Processor processObject:] + 577
    6   nib2objc                            0x000000010153a43c -[NibProcessor process] + 604
    7   nib2objc                            0x00000001015375b7 main + 439
    8   nib2objc                            0x00000001015373f4 start + 52
    9   ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by akosma** [comment]
This project is no longer maintained, sorry.
