### ISSUE TITLE
I have a Error!

### ISSUE THREAD

**Issue by nicolastinkl** [akosma/nib2objc#14]
here is the code :
nkl:Sample tinkl$ ./nib2objc TKSettingsView.xib tk.m
2016-08-19 14:25:30.829 nib2objc[2201:39772] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayI objectAtIndex:]: index 4 beyond bounds [0 .. 2]'
**\* First throw call stack:
(
        0   CoreFoundation                      0x00007fff98b7ab5c __exceptionPreprocess + 172
        1   libobjc.A.dylib                     0x00007fff9ca568e8 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff98a45f34 -[__NSArrayI objectAtIndex:] + 164
        3   nib2objc                            0x00000001011f7d3b -[NSNumber(Nib2ObjcExtensions) textAlignmentString] + 139
        4   nib2objc                            0x00000001011ffee7 -[UILabelProcessor processKey:value:] + 199
        5   nib2objc                            0x00000001011fd3dc -[Processor processObject:] + 572
        6   nib2objc                            0x00000001011fa444 -[NibProcessor process] + 596
        7   nib2objc                            0x00000001011f75e9 main + 425
        8   nib2objc                            0x00000001011f7434 start + 52
        9   ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by akosma** [comment]
nib2objc is under rewriting. it has not been updated in years, and it is not guaranteed that it works with current versions of XIBs and storyboards.

**Comment by chiliec** [comment]
> under rewriting

WOW! Where?
