### ISSUE TITLE
Doesn't handle UIImageView?

### ISSUE THREAD

**Issue by Stokestack** [akosma/nib2objc#2]
Nice work!

I do find that it doesn't generate code for UIImageViews; instead, they are instantiated as UIViews.  Is this a known problem, or intentional for some reason?

Thanks!

**Comment by akosma** [comment]
Hi,

It does generate code for UIImageViews, but what I doesn't generate is the "image" property (of type UIImage), which is not exposed by the ibtool utility.

Best,

Adrian

**Comment by Stokestack** [comment]
Thanks for the reply.  When I ran it on a XIB that had a UIImageView, it was declared simply as a UIView.
