### ISSUE TITLE
Please Update Documentation (https://github.com/akosma/nib2objc/wiki)

### ISSUE THREAD

**Issue by 1951FDG** [akosma/nib2objc#5]
nib2objc yourfile.xib > code.m (NibProcessorCodeStyleProperties) or nib2objc yourfile.xib 2 > code.m (NibProcessorCodeStyleSetter)

**Comment by 1951FDG** [comment]
Another tip for contributors (Xcode Version 3.1.4)
1. Get Info of Executable "nib2objc"
2. Under General, Use pipe for standard input/output
3. Under Arguments, add argument 'yourfile.xib' or 'yourfile.xib 2' to arguments to be passed to launch

This makes it easier to debug, as output is saved to Xcode console and you can have multiple arguments stored and switch to one of them when needed.

**Comment by xubing** [comment]
I can't get any codes under  the  os lion and the xcode 4.3.1.
Does it not support xcode 4.3.1?

**Comment by 1951FDG** [comment]
have you tried debug mode, I don't have access to xcode 4.x...

2012/3/21 xubing <
reply@reply.github.com
