### ISSUE TITLE
null for transforming some storyboard file and xib file

### ISSUE THREAD

**Issue by evoloyeu** [akosma/nib2objc#6]
below is the example code transformed in output:

//transformed from storyboard file with this command:
//  ./nib2objc MainStoryboard.storyboard 2
(null) *(null)4 = [[NSProxy alloc] init];

//   ./nib2objc TestViewController.xib
[(null)89 addSubview:viewcontroller92];

**Comment by evoloyeu** [comment]
I think that kind of object should be omitted, otherwise it sometimes may be confused.

**Comment by akosma** [comment]
Yes, sorry about that, the support for storyboards is not yet ready.
