### ISSUE TITLE
Want to access all iphone file

### ISSUE THREAD

**Issue by prateek1108** [akosma/nib2objc#8]
hi.....
i want to copy my iphone files to computer without jail-breaking my iphone. i had tried iphonebrowsercode but only able to access few files, some file are remaining how can i got access on those remaining files(sms.db,call_history.db ,etc) ....

**Comment by jlebrech** [comment]
what does that have to do with nib2objc.

try something like http://www.i-funbox.com/ (my first google results for, iphone file browser)
